CREATE TABLE T_CAUSE_TYPE (
  CAUSE_TYPE_ID SERIAL PRIMARY KEY,
  NAME VARCHAR(50) UNIQUE NOT NULL
);

CREATE TABLE T_CAUSE (
  CAUSE_ID SERIAL PRIMARY KEY,
  NAME VARCHAR(120) NOT NULL,
  DESCRIPTION VARCHAR(500) NOT NULL,
  CREATED_AT TIMESTAMP NOT NULL,
  DEADLINE TIMESTAMP,
  PLEDGED NUMERIC,
  BUDGET_REACHED NUMERIC,
  BACKERS_COUNTER NUMERIC
);

CREATE TABLE T_CAUSE_CAUSE_TYPE (
  CAUSE_TYPE_ID INTEGER REFERENCES T_CAUSE_TYPE(CAUSE_TYPE_ID),
  CAUSE_ID INTEGER REFERENCES T_CAUSE(CAUSE_ID),

  PRIMARY KEY(CAUSE_TYPE_ID, CAUSE_ID)
);

CREATE TABLE T_CAUSE_IMAGE (
  CAUSE_ID INTEGER REFERENCES T_CAUSE(CAUSE_ID),
  IMAGE BYTEA NOT NULL
);
